=== TowoLabs/token-list/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/TowoLabs/token-list/master/tokenlist.schema.json",
  "title": "Bifrost Wallet Token List",
  "description": "Schema for lists of tokens compatible with Bifrost Wallet",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [
            1,
            2
          ]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        }
      },
      "required": [
        "major",
        "minor",
        "patch"
      ]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the EVM-compatible network where this token is deployed. Enum may only include supported live networks.",
          "enum": [1, 10, 19, 56, 137, 250, 42161],
          "examples": [
            1,
            19
          ]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": [
            "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          ]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [
            18
          ]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 1,
          "maxLength": 40,
          "pattern": "^[ \\w.'+\\-%/À-ÖØ-öø-ÿ:&\\[\\]\\(\\)]+$",
          "examples": [
            "USD Coin"
          ]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token; must be alphanumeric",
          "pattern": "^[a-zA-Z0-9+\\-%/$.]+$",
          "minLength": 1,
          "maxLength": 64,
          "examples": [
            "USDC"
          ]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; must be PNG",
          "format": "uri",
          "pattern": "^https:\\/\\/raw\\.githubusercontent\\.com\\/TowoLabs\\/token-list\\/master\\/assets\\/0x[A-Fa-f0-9]{40}\\.png$",
          "examples": [
            "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x0d94e59332732d18cf3a3d457a8886a2ae29ea1b.png"
          ]
        }
      },
      "required": [
        "chainId",
        "address",
        "decimals",
        "name",
        "symbol",
        "logoURI"
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 20,
      "pattern": "^[A-Za-z ]+$",
      "examples": [
        "My Token List"
      ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "items": {
        "$ref": "#/definitions/TokenInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[a-z ]+$",
        "examples": [
          "default",
          "list"
        ]
      },
      "maxItems": 10,
      "uniqueItems": true
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the token list",
      "format": "uri",
      "enum": ["https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/bifrost-wallet.png"]
    }
  },
  "required": [
    "name",
    "timestamp",
    "version",
    "tokens",
    "logoURI"
  ]
}

=== TowoLabs/token-list/bifrost-wallet.tokenlist.json
{
    "name": "Bifrost Wallet",
    "timestamp": "2022-02-02T00:00:00+00:00",
    "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/bifrost-wallet.png",
    "version": {
        "major": 1,
        "minor": 6,
        "patch": 0
    },
    "keywords": [
        "bifrost wallet",
        "default",
        "list"
    ],
    "tokens": [
        {
            "chainId": 1,
            "address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
            "name": "Tether",
            "symbol": "USDT",
            "decimals": 6,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7.png"
        },
        {
            "chainId": 1,
            "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
            "symbol": "USDC",
            "name": "USD Coin",
            "decimals": 6,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48.png"
        },
        {
            "chainId": 1,
            "address": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
            "name": "Uniswap",
            "symbol": "UNI",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984.png"
        },
        {
            "address": "0x4Fabb145d64652a948d72533023f6E7A623C7C53",
            "chainId": 1,
            "name": "Binance USD",
            "symbol": "BUSD",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x4Fabb145d64652a948d72533023f6E7A623C7C53.png"
        },
        {
            "chainId": 1,
            "address": "0x514910771AF9Ca656af840dff83E8264EcF986CA",
            "name": "Chainlink",
            "symbol": "LINK",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x514910771AF9Ca656af840dff83E8264EcF986CA.png"
        },
        {
            "address": "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0",
            "chainId": 1,
            "name": "Polygon",
            "symbol": "MATIC",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0.png"
        },
        {
            "chainId": 1,
            "address": "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
            "name": "Wrapped Bitcoin",
            "symbol": "WBTC",
            "decimals": 8,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599.png"
        },
        {
            "chainId": 1,
            "address": "0x6B175474E89094C44Da98b954EedeAC495271d0F",
            "name": "Dai",
            "symbol": "DAI",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F.png"
        },
        {
            "chainId": 1,
            "address": "0x75231F58b43240C9718Dd58B4967c5114342a86c",
            "name": "OKB",
            "symbol": "OKB",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x75231F58b43240C9718Dd58B4967c5114342a86c.png"
        },
        {
            "address": "0x50D1c9771902476076eCFc8B2A83Ad6b9355a4c9",
            "chainId": 1,
            "name": "FTX Token",
            "symbol": "FTT",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x50D1c9771902476076eCFc8B2A83Ad6b9355a4c9.png"
        },
        {
            "address": "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
            "chainId": 1,
            "name": "Aave",
            "symbol": "AAVE",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9.png"
        },
        {
            "address": "0xBB0E17EF65F82Ab018d8EDd776e8DD940327B28b",
            "chainId": 1,
            "name": "Axie Infinity",
            "symbol": "AXS",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xBB0E17EF65F82Ab018d8EDd776e8DD940327B28b.png"
        },
        {
            "address": "0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b",
            "chainId": 1,
            "name": "Crypto.com Coin",
            "symbol": "CRO",
            "decimals": 8,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xA0b73E1Ff0B80914AB6fe0444E65848C4C34450b.png"
        },
        {
            "address": "0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE",
            "chainId": 1,
            "name": "Shiba Inu",
            "symbol": "SHIB",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE.png"
        },
        {
            "address": "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2",
            "chainId": 1,
            "name": "Maker",
            "symbol": "MKR",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2.png"
        },
        {
            "address": "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84",
            "chainId": 1,
            "name": "Lido Staked Ether",
            "symbol": "STETH",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84.png"
        },
        {
            "address": "0xD46bA6D942050d489DBd938a2C909A5d5039A161",
            "chainId": 1,
            "name": "Ampleforth",
            "symbol": "AMPL",
            "decimals": 9,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xD46bA6D942050d489DBd938a2C909A5d5039A161.png"
        },
        {
            "address": "0x2AF5D2aD76741191D15Dfe7bF6aC92d4Bd912Ca3",
            "chainId": 1,
            "name": "UNUS SED LEO",
            "symbol": "LEO",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x2AF5D2aD76741191D15Dfe7bF6aC92d4Bd912Ca3.png"
        },
        {
            "address": "0x6B3595068778DD592e39A122f4f5a5cF09C90fE2",
            "chainId": 1,
            "name": "SushiSwap",
            "symbol": "SUSHI",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x6B3595068778DD592e39A122f4f5a5cF09C90fE2.png"
        },
        {
            "chainId": 1,
            "address": "0x0000000000085d4780B73119b644AE5ecd22b376",
            "name": "TrueUSD",
            "symbol": "TUSD",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x0000000000085d4780B73119b644AE5ecd22b376.png"
        },
        {
            "chainId": 1,
            "address": "0x0D8775F648430679A709E98d2b0Cb6250d2887EF",
            "name": "Basic Attention Token",
            "symbol": "BAT",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x0D8775F648430679A709E98d2b0Cb6250d2887EF.png"
        },
        {
            "chainId": 1,
            "address": "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359",
            "name": "Sai",
            "symbol": "SAI",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.png"
        },
        {
            "chainId": 1,
            "address": "0xc00e94Cb662C3520282E6f5717214004A7f26888",
            "name": "Compound",
            "symbol": "COMP",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xc00e94Cb662C3520282E6f5717214004A7f26888.png"
        },
        {
            "address": "0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F",
            "chainId": 1,
            "name": "Synthetix",
            "symbol": "SNX",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0xC011a73ee8576Fb46F5E1c5751cA3B9Fe0af2a6F.png"
        },
        {
            "chainId": 1,
            "address": "0x221657776846890989a759BA2973e427DfF5C9bB",
            "name": "Reputation",
            "symbol": "REPv2",
            "decimals": 18,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x221657776846890989a759BA2973e427DfF5C9bB.png"
        },
        {
            "chainId": 1,
            "address": "0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5",
            "name": "Compound Ether",
            "symbol": "CETH",
            "decimals": 8,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5.png"
        },
        {
            "chainId": 1,
            "address": "0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4",
            "name": "Compound Collateral",
            "symbol": "CCOMP",
            "decimals": 8,
            "logoURI": "https://raw.githubusercontent.com/TowoLabs/token-list/master/assets/0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4.png"
        },
        {
            "chainId": 1,
            "address": "0x39AA39c021dfbaE8faC545936693aC917d5E7563",
            "name": "Compound USD Coin",
            "symbol": "CUSDC",
            "decimals": 8,
